name: Render Archetype

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: archetect/render-action@fix/tar-gz-path
        with:
          source: "."
          args: "-a org-name=p6m -a solution-name=archetypes -a project-name=langflow-blueprints"
          destination: ".contents"
